name: ditonton
description: "Submission project app for Dicoding"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  about:
    path: packages/about
  core:
    path: packages/core
  cupertino_icons: ^1.0.8
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3
  http: ^1.4.0
  movies:
    path: packages/movies
  provider: ^6.1.5
  search:
    path: packages/search
  tv_series:
    path: packages/tv_series
  watchlist:
    path: packages/watchlist
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - certificates/
